language: node_js
node_js:
  - "10"
  - "12"

cache:
  directories:
    - node_modules

notifications:
  email: false

env:
  global:
    - GH_REF="github.com/streamdasher/obs-websocket-js"
    - DEBUG="obs-websocket-js:*"

before_script:
  - npm install json -g
  - bash ./.travis/pre-build.sh
  - npm install

script:
  - npm run build
  - npm test
  - npm run node-coveralls

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: deploy
      if: branch = master
      script:
        - npm run build
        - bash ./.travis/gh-pages.sh
      node_js: 10
